== Configuration

The generated configuration, which will be generated in the root of your project, and be called conventions.groovy.
This configuration is actually a custom compilation script. For more information about custom compilation
scripts, see the Custom Compiler Script section. You can change the location of the configuration, by setting
the following property, in gradle.properties:
[source,groovy]
----
compilationScript = conventions.groovy
----

If you don't set up a configuration, the default configuration will be applied, which you can see below.

=== Default Configuration
If during the setup you choose `setupEnterpriseGroovyConventions` you will get a conventions.groovy like this:

[source,groovy]
----
Map conventions = [
        disable                     : false,
        whiteListScripts            : true,

        disableDynamicCompile       : false,
        dynamicCompileWhiteList     : [],

        compileStaticExtensions     : [],
        limitCompileStaticExtensions: false,

        defAllowed                  : true,
        allowedSuppressions         : [],
        skipDefaultPackage          : false
]

System.setProperty('enterprise.groovy.conventions', "conventions=${conventions.inspect()}")
----

* disable - This disables the Enterprise Groovy plugin, so it won't add static compilation, or do any compile-time checks.
* whiteListScripts - This will disable automatic static compilation for dynamic scripts. These scripts could be DSLs used by a framework or if you use a Groovy Shell in your code.
* disableDynamicCompile- This disables the use of `@CompileDynamic` and `@CompileStatic(TypeCheckingMode.SKIP)`. If true and `@CompileDynamic` or `@CompileStatic(TypeCheckingMode.SKIP)` is present a compilation error will be thrown.
* dynamicCompileWhiteList -  A list of file names, package names, or partial names for whitelisting classes that will not be statically compiled by default, and won't be subject to any of the Enterprise Groovy Rules.
* compileStaticExtensions - A list of Compilation extensions to be applied to the static compilation. These can be used to either make the static compilation, more, or less strict.
* limitCompileStaticExtensions - if true then only the compileStaticExtensions specified can be used. So if you manually use a @CompileStatic Annotation, you wouldn't be able to use any extensions, beyond the ones listed.
* defAllowed - If the `def` keyword is allowed for properties/fields, method returns or method parameters. If you want to restrict `def` within methods, take a look at the "Taking it a step further" section.
* allowedSuppressions - A list of strings that can be added to @SuppressWarnings to exclude a code block from requiring no `def` keyword.
* skipDefaultPackage - If set true this will whitelist any classes in the default package.

=== Grails Configuration

If during the setup you choose `setupEnterpriseGroovyGrailsConventions` you will get a conventions.groovy like this:

[source,groovy]
----
Map conventions = [
        disable                     : false,
        whiteListScripts            : true,

        disableDynamicCompile       : false,
        dynamicCompileWhiteList     : [
                'UrlMappings',
                'Application',
                'BootStrap',
                'resources',
                'org.grails.cli'
        ],

        compileStaticExtensions     : [
                'org.grails.compiler.ValidateableTypeCheckingExtension',
                'org.grails.compiler.NamedQueryTypeCheckingExtension',
                'org.grails.compiler.HttpServletRequestTypeCheckingExtension',
                'org.grails.compiler.WhereQueryTypeCheckingExtension',
                'org.grails.compiler.DynamicFinderTypeCheckingExtension',
                'org.grails.compiler.DomainMappingTypeCheckingExtension',
                'org.grails.compiler.RelationshipManagementMethodTypeCheckingExtension'
        ],

        limitCompileStaticExtensions: false,
        defAllowed                  : false, //For controllers you can use Object in place of def, and in Domains add Closure to constraints/mappings closure fields.
        allowedSuppressions         : [],
        skipDefaultPackage          : true, //For GSP files
]

System.setProperty('enterprise.groovy.conventions', "conventions=${conventions.inspect()}")
----

These are defaults that I tested, that seem to work for Grails.
