== Configuration

The configuration which will be generated in the root of your project. This is required for the plugin
to be able to find it. If the plugin can't find the configuration, or if you didin't set one up the default
configuration will be applied, which you can see below.

Also for the configuration to be picked up, you have to build to one of the following directories:

* build
* target
* output

`build` is the default directory, that gradle builds to, so if you don't change it everything should work.

=== Default Configuration
If during the setup you choose `setupEnterpriseGroovyConventions` you will get a conventions.groovy like this:

[source,groovy]
----
conventions = [
        disableDynamicCompile       : false,
        dynamicCompileWhiteList     : [],

        compileStaticExtensions     : [],
        limitCompileStaticExtensions: false,
        defAllowed                  : true,
        skipDefaultPackage          : false
]
----

* disableDynamicCompile- This disables the use of `@CompileDynamic`. If true and `@CompileDynamic` is present a compilation error will be thrown.
* dynamicCompileWhiteList -  A list of file names, package names, or partial names for white listing classes that will not be statically compiled by default, and won't be subject to any of the Enterprise Groovy Rules.
* compileStaticExtensions - A list of Compilation extensions to be applied to the static compilation. These can be used to either make the static compilation, more, or less strict.
* limitCompileStaticExtensions - if true then only the compileStaticExtensions specified can be used. So if you manually use a @CompileStatic Annotation, you wouldn't be able to use any extensions, beyond the ones listed.
* defAllowed - If the `def` keyword is allowed for properties/fields, method returns or method parameters. If you want to restrict de within methods, take a look at the "Taking it a step further" section.
* skipDefaultPackage - If set true this will whitelist any classes in the default package.

=== Grails Configuration

If during the setup you choose `setupEnterpriseGroovyGrailsConventions` you will get a conventions.groovy like this:

[source,groovy]
----
conventions = [
        disableDynamicCompile       : true,
        dynamicCompileWhiteList     : [
                'UrlMappings',
                'Application',
                'Script1',
                'BootStrap',
                'resources',
                'org.grails.cli'
        ],

        compileStaticExtensions     : [
                'org.grails.compiler.ValidateableTypeCheckingExtension',
                'org.grails.compiler.NamedQueryTypeCheckingExtension',
                'org.grails.compiler.HttpServletRequestTypeCheckingExtension',
                'org.grails.compiler.WhereQueryTypeCheckingExtension',
                'org.grails.compiler.DynamicFinderTypeCheckingExtension',
                'org.grails.compiler.DomainMappingTypeCheckingExtension',
                'org.grails.compiler.RelationshipManagementMethodTypeCheckingExtension'
        ],

        limitCompileStaticExtensions: true,
        defAllowed                  : false, //For controllers you can use Object in place of def, and in Domains add Closure to constraints/mappings closure fields.
        skipDefaultPackage          : true,  //For GSP files
]
----

These are defaults that I tested, that seem to work for Grails.