== Getting Started

To get started, install the Enterprise Groovy plugin, in your `build.grade`:

Using the plugins DSL:
[source,groovy]
----
plugins {
  id "enterprise.groovy.plugin" version "1.0"
}
----
Using legacy plugin application:
[source,groovy]
----
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "com.virtualdogbert:enterprise-groovy-plugin:1.0"
  }
}
----

Then run one of the setup Gradle tasks `setupEnterpriseGroovyConventions` or `setupEnterpriseGroovyGrailsConventions`. This will provide
you with a `conventions.groovy` file in the root of your project, that you can use to configure the
Enterprise Groovy Plugin.

WARNING: If you apply the Enterprise Groovy plugin to an existing project, you may have a lot of compilation errors based on
static compilation. To start if you have a lot of classes that break, you may want to add them
temporarily, to the whitelist, and iteratively upgrade them, to be statically compilable.

=== Example applications

Here is an example app with commented out code that will cause the build to fail, because of the static
compilation, or rules set in the conventions.groovy:

* https://github.com/virtualdogbert/test-enterprise-groovy[GitHub test-enterprise-groovy]

Here is another application which has a different setup, and was used to debug some issues:

* https://github.com/virtualdogbert/SUPPLIES[GitHub SUPPLIES]
