== Getting Started

To get started install the Enterprise Groovy plugin, in your `build.grade`:

[source,groovy]
----
buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath 'com.virtualdogbert:enterprise-groovy-plugin:1.0.RC2'
    }
}

apply plugin: "enterprise.groovy.plugin"
----

WARNING: For now do not use the new way of adding gradle plugins like below. This will cause the Enterprise
Groovy plugin not to function properly. More research is required to get this working, and  will be released
in a future version of Enterprise Groovy.
[source,groovy]
----
plugins {
  id "enterprise.groovy.plugin" version "1.0.RC2"
}
----

Then run one of the setup Gradle tasks `setupEnterpriseGroovyConventions` or `setupEnterpriseGroovyGrailsConventions`. This will provide
you with a `conventions.groovy` file in the root of your project, that you can use to configure the
Enterprise Groovy Plugin.

WARNING: If you apply the Enterprise Groovy plugin to an existing project, you may have a lot of compilation errors based on
static compilation. To start if you have a lot of classes that break, you may want to add them
temporarily, to the whitelist, and iterative upgrade them to be statically compilable.

=== Example applications

Here is an example app with commented out code that will cause the build to fail, because of the static
compilation, or rules set in the conventions.groovy:

* https://github.com/virtualdogbert/test-enterprise-groovy[GitHub test-enterprise-groovy]

* https://github.com/virtualdogbert/SUPPLIES[GitHub SUPPLIES]
