== Getting Started

1.  To get started install the Enterprise Groovy plugin, in your `build.grade`:

[source,groovy]
----
plugins {
  id "enterprise.groovy.plugin" version "1.0.RC1"
}
----

Or the older way:

[source,groovy]
----
buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath 'com.virtualdogbert:enterprise-groovy-plugin:1.0.R1'
    }
}

apply plugin: "enterprise.groovy.plugin"
----
2. Run one of the setup Gradle tasks `setupEnterpriseGroovyConventions` or `setupEnterpriseGroovyGrailsConventions`. This will provide
you with a `conventions.groovy` file in the root of your project, that you can use to configure the
Enterprise Groovy Plugin.

=== A word of caution
If you apply the Enterprise Groovy plugin to an existing project, you may have a lot of compilation errors based on
static compilation. To start if you have a lot of classes that break, you may want to add them
temporarily, to the whitelist, and iterative upgrade them to be statically compilable.

=== Example applications

Here is an example app with commented out code that will cause the build to fail, because of the static
compilation, or rules set in the conventions.groovy:

https://github.com/virtualdogbert/test-enterprise-groovy[GitHub test-enterprise-groovy]

