== Version History
* 1.0.1
* Fixed an issue with a transient dependency when used in a library, that was retrieved with an @Grab.
* 1.0
** Fixed loop hole for disabling dynamic compilation by disallowing `@CompileStatic(TypeCheckingMode.SKIP)` in addition to `@CompileDynamic`.
** Getting more of the configuration to the console task.
** Fixing some typos, and updating documentation.
* 1.0.RC4
** Fixed issue getting config to the AST transform, using a custom compiler script.
** Fixed issue, where Enterprise Groovy becomes a transient dependency.
** Fixed issues with Gradle 5 not being able to use the plugin DSL.
** Updated the documentation.
* 1.0.RC3
** Scripts like those from a Groovy shell will be skipped automatically for static compilation.
This is because there is no way currently to get the configuration during compilation from the script.
** Changing the plugin to add the Enterprise Groovy library to the project, using `implementation`, rather,
then `compile`, to avoid introducing transient dependencies.
* 1.0.RC2
** Fixing some issues related to Gradle 5, and not being able to find the config.
** Fixing an issue with the Groovy Console also related to Gradle 5. If the property sourceSets
is not available then the Groovy Console will not be available, see the getting started section for
more details.
* 1.0.RC1
** Initial Release with compile static by default and configuration for enforcement.
